# Generated by Django 5.2.9 on 2026-01-06 03:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_join_date_alter_message_msg_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
