# Generated by Django 5.2.9 on 2026-01-09 10:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=api.models.generate_product_id, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(default=api.models.get_random_avatar),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=api.models.generate_user_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
